name: sar
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.21 
  - pandas=
  - scikit-learn
  - seaborn
  - networkx
  - gensim=4.1.2
  - scipy
  - tqdm
  - nltk
  - matplotlib
  - pillow
  - pip
  - pip:
      - plotly
      - openai
      - transformers
      - spacy
      - torch
      - selenium
      - umap-learn
      - wordcloud
