name: sar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21  # compatible con Python 3.9 y otras librerías científicas
  - pandas=1.3
  - scikit-learn=0.24
  - seaborn=0.11
  - networkx=2.5
  - gensim=4.1.2
  - scipy=1.7
  - tqdm=4.62
  - nltk=3.6
  - matplotlib=3.4
  - pillow=8.2
  - pip
  - pip:
      - streamlit==0.89
      - plotly==5.3
      - openai==0.10
      - transformers==4.11
      - spacy==3.2
      - torch==1.10
      - selenium==4.0.0
      - umap-learn==0.5.1
      - wordcloud==1.8.1
