name: sar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21
  - pip
  - pandas
  - scikit-learn
  - seaborn
  - networkx
  - gensim=4.3.3
  - scipy
  - tqdm
  - nltk
  - pip:
      - streamlit
      - plotly
      - openai
      - transformers
      - spacy
      - torch
      - selenium
      - umap-learn
      - wordcloud
      - matplotlib
      - pillow
