name: sar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - altair=4.1.0
  - pip:
      - ace-tools==0.0
      - annotated-types==0.7.0
      - attrs==24.2.0
      - blis==1.0.1
      - catalogue==2.0.10
      - cloudpathlib==0.19.0
      - confection==0.1.5
      - contourpy==1.3.0
      - cycler==0.12.1
      - cymem==2.0.8
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - filelock==3.16.1
      - fonttools==4.54.1
      - fsspec==2024.9.0
      - gensim==4.3.3
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.25.1
      - importlib-resources==6.4.5
      - jiter==0.6.1
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - langcodes==3.4.1
      - language-data==1.2.0
      - libarchive
      - llvmlite==0.43.0
      - marisa-trie==1.2.0
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - murmurhash==1.0.10
      - networkx==3.2.1
      - nltk==3.9.1
      - numba==0.60.0
      - openai==1.51.2
      - outcome==1.3.0.post0
      - patsy==0.5.6
      - playwright==1.47.0
      - plotly==5.24.1
      - preshed==3.0.9
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyee==12.0.0
      - pynndescent==0.5.13
      - pyparsing==3.1.4
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - regex==2024.9.11
      - rich==13.9.1
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - selenium==4.24.0
      - shellingham==1.5.4
      - smart-open==7.0.4
      - sortedcontainers==2.4.0
      - spacy==3.8.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - statsmodels==0.14.4
      - sympy==1.13.3
      - tenacity==9.0.0
      - thinc==8.3.2
      - threadpoolctl==3.5.0
      - tokenizers==0.20.0
      - torch==2.2.2
      - tqdm==4.66.5
      - transformers==4.45.1
      - trio==0.26.2
      - trio-websocket==0.11.1
      - typer==0.12.5
      - umap==0.1.1
      - umap-learn==0.5.6
      - wasabi==1.1.3
      - weasel==0.4.1
      - webdriver-manager==4.0.2
      - wordcloud==1.9.3
      - wrapt==1.16.0
      - wsproto==1.2.0
